version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=mss-metro-ai_default
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
    networks:
      - default

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    ports:
      - "11211:11211"
    command: memcached -m 64
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-lambda
    ports:
      - "9000:8080"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - S3_BUCKET=mss-metro-images
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/image-processing
      - RAG_SERVICE_URL=http://host.docker.internal:8001
      - CACHE_HOST=memcached
      - CACHE_PORT=11211
    depends_on:
      - localstack
      - memcached
    networks:
      - default

volumes:
  localstack-data:

networks:
  default:
    name: mss-metro-ai_default
